[package]
name = "flexblock-db"
version = "0.1.0"
authors = ["Albert Garde <albertsgarde@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
