[package]
name = "flexblock"
version = "0.1.0"
authors = ["Albert Garde"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = { version = "0.9.1", features = ["serde"] }
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"
typetag = "0.1.7"
tokio = { version = "1.3.0", features = ["full"] }
