[package]
name = "world-generation"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = {path = "../utils"}

nalgebra-glm = { version = "0.11.*", features = ["serde-serialize"] }
log = "0.4.*"
